-- MySQL Script generated by MySQL Workbench
-- Sun Nov 27 20:46:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Carteira Digital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carteira Digital` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carteira Digital` (
  `idCarteira Virtual` INT NOT NULL,
  `Numero da Carteira` INT NULL,
  `Data da Adesão` DATE NULL,
  `Valor em conta` FLOAT NULL,
  `Valor de Cashback` FLOAT NULL,
  PRIMARY KEY (`idCarteira Virtual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data de Nascimento` DATE NULL,
  `Identificação` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Telefone 1` VARCHAR(45) NOT NULL,
  `Telefone 2` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Conta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Conta` (
  `idConta` INT NOT NULL,
  `Tipo de Conta` VARCHAR(45) BINARY NOT NULL DEFAULT 'Pessoa Fisica/Pessoa Juridica',
  `CPF/CNPJ` INT NOT NULL DEFAULT Digite somente numeros,
  `Fundação/Aniversário` DATE NOT NULL,
  `Atividade economica/Profissão` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idConta`, `Cliente_idCliente`),
  INDEX `fk_Conta_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Conta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibilizando um Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disponibilizando um Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilizando um Produto` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Fornecedor_has_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC),
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa de Frete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empresa de Frete` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empresa de Frete` (
  `idEmpresa de Frete` INT NOT NULL,
  `Razão Social` VARCHAR(45) NOT NULL,
  `Nome Fantasia` VARCHAR(45) NOT NULL,
  `CNPJ` INT NOT NULL,
  `Responsavel` VARCHAR(45) NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `E-mail 2` VARCHAR(45) NULL,
  `Telefone 1` INT NOT NULL,
  `Telefone 2` INT NULL,
  PRIMARY KEY (`idEmpresa de Frete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `Código de rastreio` INT NOT NULL,
  `Status da entrega` VARCHAR(45) NOT NULL,
  `Prazo de Entrega(em dias)` INT NOT NULL,
  `Valor Frete` FLOAT NOT NULL,
  `Empresa de Frete_idEmpresa de Frete` INT NOT NULL,
  PRIMARY KEY (`idEntrega`, `Empresa de Frete_idEmpresa de Frete`),
  INDEX `fk_Entrega_Empresa de Frete1_idx` (`Empresa de Frete_idEmpresa de Frete` ASC),
  CONSTRAINT `fk_Entrega_Empresa de Frete1`
    FOREIGN KEY (`Empresa de Frete_idEmpresa de Frete`)
    REFERENCES `mydb`.`Empresa de Frete` (`idEmpresa de Frete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NOT NULL,
  `Responsavel` VARCHAR(45) NOT NULL,
  `E-mail 1` VARCHAR(45) NOT NULL,
  `E-mail 2` VARCHAR(45) NULL,
  `Telefone 1` INT NOT NULL,
  `Telefone 2` INT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Formas de Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Formas de Pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Formas de Pagamento` (
  `Cliente_idCliente` INT NOT NULL,
  `Pagamento em Cartão_idForma de Pagamento` INT NOT NULL,
  `Carteira Digital_idCarteira Virtual` INT NOT NULL,
  `Pix` VARCHAR(45) NULL,
  `Boleto Bancário` VARCHAR(45) NULL,
  `Tranferência Bancária` VARCHAR(45) NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Pagamento em Cartão_idForma de Pagamento`, `Carteira Digital_idCarteira Virtual`),
  INDEX `fk_Cliente_has_Pagamento em Cartão_Pagamento em Cartão1_idx` (`Pagamento em Cartão_idForma de Pagamento` ASC),
  INDEX `fk_Cliente_has_Pagamento em Cartão_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Formas de Pagamento_Carteira Digital1_idx` (`Carteira Digital_idCarteira Virtual` ASC),
  CONSTRAINT `fk_Cliente_has_Pagamento em Cartão_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Pagamento em Cartão_Pagamento em Cartão1`
    FOREIGN KEY (`Pagamento em Cartão_idForma de Pagamento`)
    REFERENCES `mydb`.`Pagamento em Cartão` (`idForma de Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formas de Pagamento_Carteira Digital1`
    FOREIGN KEY (`Carteira Digital_idCarteira Virtual`)
    REFERENCES `mydb`.`Carteira Digital` (`idCarteira Virtual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NOT NULL,
  `Nome Fantasia` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Responsavel` VARCHAR(45) NOT NULL,
  `Contato - E-mail` VARCHAR(45) NOT NULL,
  `Contato - E-mail 2` VARCHAR(45) NULL,
  `Contato - Telefone 1` INT NOT NULL,
  `Contato - Telefone 2` INT NULL,
  `Contato - Telefone 3` INT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento em Cartão`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento em Cartão` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento em Cartão` (
  `idForma de Pagamento` INT NOT NULL,
  `Nome do Titular` VARCHAR(45) NOT NULL,
  `Número do Cartão` INT NOT NULL DEFAULT 0000 0000 0000 0000,
  `Bandeira do Cartão` VARCHAR(45) NOT NULL,
  `Data de Validade` DATE NOT NULL DEFAULT mm/aaaa,
  `CPF/CNPJ do Titular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idForma de Pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Status do Pedido` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Data do Pedido` DATE NOT NULL,
  `Valor Total do Pedido` FLOAT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Entrega_idEntrega`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idEntrega` ASC),
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Valor Unitário` FLOAT NOT NULL,
  `Possui garantia` VARCHAR(45) BINARY NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto Disponivel em Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto Disponivel em Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto Disponivel em Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC),
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos por Vendedor (terceiro)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos por Vendedor (terceiro)` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos por Vendedor (terceiro)` (
  `Terceiro - Vendedor_idTerceiro - Vendedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`, `Produto_idProduto`),
  INDEX `fk_Terceiro - Vendedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1_idx` (`Terceiro - Vendedor_idTerceiro - Vendedor` ASC),
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1`
    FOREIGN KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`)
    REFERENCES `mydb`.`Terceiro - Vendedor` (`idTerceiro - Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação de Produto/Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Relação de Produto/Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Relação de Produto/Pedido` (
  `Pedido_idPedido` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Produto_idProduto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terceiro - Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terceiro - Vendedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terceiro - Vendedor` (
  `idTerceiro - Vendedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NOT NULL,
  `Nome Fantasia` VARCHAR(45) NULL,
  `CPF/CNPJ` INT NOT NULL,
  `Local` VARCHAR(45) NOT NULL,
  `Nome Vendedor` VARCHAR(45) NOT NULL,
  `E-mail 1` VARCHAR(45) NOT NULL,
  `E-mail 2` VARCHAR(45) NULL,
  `Telefone 1` INT NOT NULL,
  `Telefone 2` INT NULL,
  PRIMARY KEY (`idTerceiro - Vendedor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
